name: CI
on:
  push:
    branches:
      - main
      - /^release-.*$/
    paths:
      - '.github/workflows/CI.yml'
      - 'test/**'
      - 'src/**'
      - 'Project.toml'
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - '.github/workflows/CI.yml'
      - 'test/**'
      - 'src/**'
      - 'Project.toml'
jobs:
  test:
    name: Julia ${{ matrix.version }} - Legolas ${{ matrix.legolas-version }} - Flux ${{ matrix.flux-version }} - ${{ github.event_name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        legolas-version:
          - '0.2'
          - '0.3'
        flux-version:
          - '0.12'
          - '0.13'
        version:
          - '1' # current release
        include:
          - version: '1.5' # earliest supported version
            legolas-version: '0.2'
            flux-version: '0.12'
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: x64
      - name: "Install Legolas and Flux"
        shell: julia --color=yes --project=. {0}
        run: |
          using Pkg
          Pkg.add([Pkg.PackageSpec(; name="Legolas", version="${{ matrix.legolas-version }}"),
                   Pkg.PackageSpec(; name="Flux", version="${{ matrix.flux-version }}")])
      - uses: actions/cache@v2
        with:
          path: ~/.julia/artifacts
          key: ${{ runner.os }}-test-artifacts-${{ hashFiles('**/Project.toml') }}
          restore-keys: ${{ runner.os }}-test-artifacts
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v2
        with:
          file: lcov.info
