name: CI
on:
  push:
    branches:
      - main
      - /^release-.*$/
    paths:
      - '.github/workflows/CI.yml'
      - 'test/**'
      - 'src/**'
      - 'Project.toml'
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - '.github/workflows/CI.yml'
      - 'test/**'
      - 'src/**'
      - 'Project.toml'
jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1.5' # earliest supported version
          - '1' # current release
        os:
          - ubuntu-latest
        arch:
          - x64
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.BEACONBUDDY_SSH_KEY }}
      - name: Set up registries
        run: |
          git config --global url.git@github.com:.insteadOf https://github.com/
          git clone git@github.com:JuliaRegistries/General.git ~/.julia/registries/General
          git clone git@github.com:beacon-biosignals/BeaconRegistry.git ~/.julia/registries/Beacon
      - uses: actions/cache@v2
        with:
          path: ~/.julia/artifacts
          key: ${{ runner.os }}-test-artifacts-${{ hashFiles('**/Project.toml') }}
          restore-keys: ${{ runner.os }}-test-artifacts
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: lcov.info
